name: 'Composite Action Summary Test'
description: 'Composite Action Summary Test'

runs:
  using: "composite"
  steps:
    - if: ${{ success() }}
      shell: bash
      run: |
        echo "### Composite Step: 1." >> $GITHUB_STEP_SUMMARY
    - if: ${{ success() }}
      shell: bash
      run: |
        echo "### Composite Step: 2." >> $GITHUB_STEP_SUMMARY
    - if: ${{ success() }}
      shell: bash
      run: |
        echo "### Composite Step: 3." >> $GITHUB_STEP_SUMMARY